### ISSUE TITLE
UI impressions with Chrome/Safari on iPhone 6

### ISSUE THREAD

**Issue by dasniko** [dukecon/dukecon_html5#53] opened 2016-01-30 17:03 UTC
I made the following experiences today, when surfing with iPhone 6 and Chrome (Safari is same behaviour, I tested it, but did no screenshots):

_Caution: Screenshots are very big, sorry..._
### Cookie-Banner

The Cookie-Banner has no 100% width. Is this inteded? The fist test showed even a much smaller cookie overlay, but I couldn't reproduce.
![2016-01-30 12 47 06](https://cloud.githubusercontent.com/assets/2075748/12697072/3d557560-c77a-11e5-83d6-02a12fd5d89a.png)
### Current Production Sites
- Startpage, content doesn't fit into the table boxes, page content very small, not a good fit for touch screen!
- When Filter is open, page content is even smaller than when it's not opened, also the header/title
- After filter is closed, page content has wrong scrolling
  ![2016-01-30 12 47 56](https://cloud.githubusercontent.com/assets/2075748/12697101/0f05e072-c77b-11e5-84a4-f7d13dc533d4.png)
  ![2016-01-30 12 48 00](https://cloud.githubusercontent.com/assets/2075748/12697102/141788ea-c77b-11e5-9f9d-27f810b133d7.png)
  ![2016-01-30 12 48 04](https://cloud.githubusercontent.com/assets/2075748/12697103/18ef5334-c77b-11e5-8147-d71c1ab92819.png)
### Current Dev Sites:
- similar behaviour/layout as on production
- startpage looks better
  ![2016-01-30 12 48 12](https://cloud.githubusercontent.com/assets/2075748/12697122/884c5ea2-c77b-11e5-98cd-76d771be9af5.png)
  ![2016-01-30 12 48 15](https://cloud.githubusercontent.com/assets/2075748/12697123/8b5dffd8-c77b-11e5-8741-4fbd8ae9dd19.png)
  ![2016-01-30 12 48 19](https://cloud.githubusercontent.com/assets/2075748/12697124/8f8b5ae2-c77b-11e5-9f84-2afe0d4973ee.png)

**Comment by steffchep** [comment] 2016-02-05 08:40
Layout on smaller screens has already been improved - can you try again on the latest build?
As for the width of the cookie overlay - this is a compromise to avoid having it bleed out of the screen - and was tested only with very large (> 1200) and 320 pixels.

**Comment by dasniko** [comment] 2016-02-07 16:27
Just tested on Latest. Still same behavior as last three screenshots.

**Comment by annam002** [comment] 2016-03-07 16:29
Can you explain what exactly the problem is in the last three screenshots?

**Comment by steffchep** [comment] 2017-03-17 15:43
I've looked at the site on an iPhone 6Plus, iOS10 and it seems to look okay. (the Cookie disclaimer is still missing a few pixels but that's not a dealbreaker - it will likely be removed entirely soon)
Closing for now.

**Closed as completed by steffchep** 2017-03-17 15:43 UTC
Labels: bug
